services:
  opp-backend:
    build:
      context: .
      dockerfile: Containerfile.dev
    environment:
      DEBUG_MODE: true
      OPP_AUTH_DB_HOST: 172.17.0.1
      OPP_AUTH_DB_PORT: 5433
      POSTGRES_AUTH_USER: user
      POSTGRES_AUTH_PASSWORD: password
      POSTGRES_AUTH_DB: db
    volumes:
      - .:/src/
    ports:
      - "8090:8090"
    depends_on:
      - opp-postgres-auth
  opp-postgres-auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
